---
- name: Test connectivity to AWS
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/localhost/vault.yml
  tasks:
    - name: provision a single ec2 instance
      ec2:
        key_name: dev-network
        instance_type: t2.micro
        image: ami-9887c6e7
        group: kikicloud-public
        wait: true
        count: 2 #"{{ num }}"
        vpc_subnet_id: subnet-0ade37adde413715a
        assign_public_ip: yes
        aws_access_key: "{{ vault_ec2_access_key }}"
        aws_secret_key: "{{ vault_ec2_secret_key }}"
        region: us-east-1
        instance_tags:
          Name: WebServer #"{{ nametag }}"
          Env: Dev
          OS: CentOS
      register: ec2
    - name: Hold on a darn second for those instances to get tagged
      pause:
        minutes: 1

